### PR TITLE
Fix RunningTimeEntry is not set to null when stopped in other sources

### LINKED ISSUE #4652: Time entry stopped in another client is not properly displayed in Windows Timeline UI
### 💻 Environment
Platform: Windows
Toggl Version: 7.5.377

### 🐞 Actual behavior
Stopped time entry is displayed as running in the Timeline UI

### 💯 Expected behavior
Stopped time entry is properly displayed in the Timeline UI

### 🔨 Steps to reproduce
1. Start a time entry
2. Open the web app
3. Stop a time entry in the web app

### 📦 Additional info

image

### PR DESCRIPTION
**Pull request by atsvirchkova**
### 📒 Description
Fix RunningTimeEntry is not set to null when stopped in other sources

### 🕶️ Types of changes

- **Bug fix** (non-breaking change which fixes an issue)

### 👫 Relationships

 Closes #4652 

### 🔎 Review hints
Testing:
1. Start TE and check it's started in timeline UI.
2. Stop TE in browser (or other clients) and check it's stopped in timeline UI.

### CODE REVIEW

File: src/ui/windows/TogglDesktop/TogglDesktop/Toggl.cs [hunk 1]
```diff
@@ -930,6 +929,7 @@ public static TogglRgbColor GetAdaptiveRgbColorFromHex(string hexColor, TogglAda
     public static readonly BehaviorSubject<DateTime> TimelineSelectedDate = new BehaviorSubject<DateTime>(DateTime.Today);
 
     public static readonly BehaviorSubject<TogglTimeEntryView?> RunningTimeEntry = new BehaviorSubject<TogglTimeEntryView?>(null);
+    public static IObservable<Unit> StoppedTimerState = RunningTimeEntry.Where(te => te == null).Select(_ => new Unit());
```
Comment (skel35) [inline src/ui/windows/TogglDesktop/TogglDesktop/Toggl.cs:932]: minor: by convention `Unit.Default` is used instead of `new Unit()` (just to avoid using `new` keyword as much as possible, I suppose). Using `default` is also fine.

**Review by skel35 — APPROVED** [review]
just one minor comment
looks good otherwise 👌

**Comment by atsvirchkova** [comment]
Good point, thanks. Fixed now.
