### PR TITLE
Revert "Fix key detection for media keys on Linux"

### LINKED ISSUE #4580: Global Ctrl + F10 shortcut breaks Ctrl completely in X11
### 💻 Environment
Platform: Linux
Toggl Version: 7.5.324

### 🔨 Steps to reproduce
1. Set a global keyboard shortcut in TogglDesktop to Ctrl+F10
2. Try if it works when a different app is in focus
3. Try if Ctrl works in another app (like Ctrl+A to select text)

### 🐞 Actual behavior
Ctrl doesn't work in other apps

### 💯 Expected behavior
Ctrl should work same as before for other shortcuts.

### 📦 Additional info
Introduced with 453cdcb5e271ea7c411f2417f6f5ee318fda7f78 (which fixed other issues though)
https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481304722762

### PR DESCRIPTION
**Pull request by skel35**
Reverts toggl-open-source/toggldesktop#4416 due to introduced #4580 which is non-trivial to fix. More comprehensive solution for #4415 is needed.

Reopens #4415.
Closes #4580.

### CODE REVIEW

File: third_party/qxtglobalshortcut5/gui/xcbkeyboard.h [hunk 1]
```diff
@@ -1,571 +0,0 @@
...
-    XK_dead_doubleacute,        Qt::Key_Dead_Doubleacute,
-    XK_dead_caron,              Qt::Key_Dead_Caron,
-    XK_dead_cedilla,            Qt::Key_Dead_Cedilla,
-    XK_dead_ogonek,             Qt::Key_Dead_Ogonek,
-    XK_dead_iota,               Qt::Key_Dead_Iota,
-    XK_dead_voiced_sound,       Qt::Key_Dead_Voiced_Sound,
-    XK_dead_semivoiced_sound,   Qt::Key_Dead_Semivoiced_Sound,
-    XK_dead_belowdot,           Qt::Key_Dead_Belowdot,
-    XK_dead_hook,               Qt::Key_Dead_Hook,
-    XK_dead_horn,               Qt::Key_Dead_Horn,
```
Comment (thomwiggers) [inline third_party/qxtglobalshortcut5/gui/xcbkeyboard.h:413]: Maybe just deleting these keys solves the problem?
