### PR TITLE
Fix quitting the app doesn't end the process on Windows 7

### LINKED ISSUE #4682: Application doesn't launch on Windows 7
### 💻 Environment

Platform: Windows
OS Version: Windows 7
Toggl Version: 7.5.383

### 🐞 Actual behavior
Toggl process stays in Task Manager after app quit.

### 💯 Expected behavior
No Toggl processed must stay alive after app quit.

### 🔨 Steps to reproduce

1. Start Windows 7 and run Toggl Track.
2. Quit Toggl Track and see that its process stays in Task manager.
3. It's impossible to start Toggl Track again until the process is killed in Task manager.

### 📦 Additional info
It's reproducible ONLY after Windows 7 restart, so to reproduce it once more it's necessary to reboot Windows.

### PR DESCRIPTION
**Pull request by atsvirchkova**
### 📒 Description
Fix quitting the app doesn't end the process on Windows 7

### 🕶️ Types of changes

 - **Bug fix** (non-breaking change which fixes an issue) 

### 👫 Relationships

Closes #4682 

### 🔎 Review hints
Like in #4331 `Process.GetCurrentProcess().Kill()` is used here. I inserted a check for Windows version to do that only for Windows 7, but for Windows 10 it also works OK, just feels like incorrect process ending.

### CODE REVIEW

File: src/ui/windows/TogglDesktop/TogglDesktop/Program.cs [hunk 1]
```diff
@@ -45,7 +45,10 @@ private static void OnBeforeStartup()
     public static void Shutdown(int exitCode)
     {
         Toggl.Clear();
-        Environment.Exit(exitCode);
+        if (Environment.OSVersion.Version.Major == 6 && Environment.OSVersion.Version.Minor == 1)
```
Comment (skel35) [inline src/ui/windows/TogglDesktop/TogglDesktop/Program.cs:48]: It is unclear what exactly this means by just reading it (even though I understand this and could look up to which Windows version this corresponds to).
I'd extract an extension or utility method (smth like `IsWindows7()`) + maybe add a small comment about this issue.

**Review by skel35 — CHANGES_REQUESTED** [review]

File: src/ui/windows/TogglDesktop/TogglDesktop/Program.cs (hunk 1 above)
Comment (atsvirchkova) [reply src/ui/windows/TogglDesktop/TogglDesktop/Program.cs]: Good point, thanks.
Fixed now.

**Review by skel35 — APPROVED** [review]
Looks good
