### PR TITLE
Fix two leaks in the library

### LINKED ISSUE #3813: Small memory leak issue
### 💻 Environment
Platform: macOS
OS Version: 10.14.6
Toggl Version: 7.5.42

### 🐞 Actual behavior
A follow-up on #3766: Further monitoring of memory use indicate a small memory leak.  Upon opening the Toggl application, the memory use is at ~60MB.  Over time, it has been seen to rise gradually. Most recently, it's been seen at 280MB after the application has been opened for over 5 days. Others have reported memory usage of ~100MB at most.  Certainly the patch in 7.5.42 fixed the high memory leak, but perhaps there is a secondary leak.  For comparison, the memory usage level is comparable to Google Chrome.

### 💯 Expected behavior
Lower memory usage

### 🔨 Steps to reproduce

1. Start Toggl on macOS 10.14.6
2. Monitor memory usage with time

### 📦 Additional info
This does not appear to affect older Mac (e.g., Mac OSX 10.11.6)

Here's a screenshot of memory usage:
Screen Shot 2020-02-16 at 9 58 11 AM

### PR DESCRIPTION
**Pull request by jiri**
### 🕶️ Types of changes

- **Bug fix** (non-breaking change which fixes an issue)

### 👫 Relationships

Closes #3813

### CODE REVIEW

File: src/toggl_api_private.cc [hunk 1]
```diff
@@ -23,7 +23,6 @@ TogglAutocompleteView *autocomplete_item_init(const toggl::view::Autocomplete &i
     result->ProjectLabel = copy_string(item.ProjectLabel);
     result->ClientLabel = copy_string(item.ClientLabel);
     result->ProjectColor = copy_string(item.ProjectColor);
-    result->WorkspaceName = copy_string(item.WorkspaceName);
```
Comment (NghiaTranUIT) [inline src/toggl_api_private.cc:26]: It's great to discover this leaking when we setting `WorkspaceName` twice 👍

**Comment by NghiaTranUIT** [comment]
I found a leak at https://github.com/toggl-open-source/toggldesktop/blob/5710632c7d8d2aa2feaf05e339b9ae845e931903/src/toggl_api_private.cc#L171

We forget to release `char_t *Code;` from `TogglCountryView`
