### PR TITLE
Stop sending sync requests when time entry fails to sync

### LINKED ISSUE #4173: Loop requests if Time Entry doesn't meet the Workspace Constraints
### Description
A lot of requests are made frequently if the Time Entry doesn't meet the Workspace constraints

### 💻 Environment
Platform: Library / mac
OS Version: macOS 10.15
Toggl Version: 7.5.172

### 🐞 Actual behavior
- A lot of requests are made and they repeat forever

### 💯 Expected behavior
- If one of sync requests are failed, we should retry after certain of seconds (back-off)

### 🔨 Steps to reproduce
1. Go to Toggl Dashboard web, enable "Required Task for Time Entry" 
2. Log in to Toggl Desktop app
3. Create some Time Entry that doesn't have task
4. CMD+R for syncing
5. Open any HTTP Debugging app
6. Observe that the Toggl Desktop makes a lot of requests repeatably without any backoff mechanism.

### LINKED ISSUE #4181: Investigate increased amount of requests
### 💻 Environment
Platform: Windows (probably Library)
Toggl Version: reproduced after a release of Windows 7.5.162, may affect other platforms as well.

### 🐞 Actual behavior
An increased amount of requests, total server load from desktop apps is up almost 2x compared to a few months ago.

### 💯 Expected behavior
Total server load should be close to what was a few months ago, +- accounting for the change in number of users.

### 🔨 How to investigate
1. Using a web debugging proxy tool (e.g. Fiddler on Windows) compare the number of requests between last Windows apps stable versions: 7.5.46 and 7.5.162. 
Since 7.5.46 doesn't work due to certificate issue, the way we can check it is by checking it out from Git and building it in Release mode (cherry-pick the certificate fix to make sure it works)
2. We can also check the same for macOS apps and compare, let's say, 7.5.42 and 7.5.172.

### 📦 Additional info
Slack link https://toggl.slack.com/archives/C0142GFJT0R/p1592386679218200

### LINKED ISSUE #4310: Fix the "Currently running time entry has unmet constraints" error
### 💻 Environment
Platform: macOS/Windows/Linux

### 📒 Description
[57.8K out of 150K Bugsnag errors](https://app.bugsnag.com/toggldesktop/toggldesktop/timeline?filters[event.since][0][type]=eq&filters[event.since][0][value]=30d&filters[error.status][0][type]=eq&filters[error.status][0][value]=open&filters[search][0][type]=eq&filters[search][0][value]=Currently&filters[search][1][type]=eq&filters[search][1][value]=running&filters[search][2][type]=eq&filters[search][2][value]=time&filters[search][3][type]=eq&filters[search][3][value]=entry&filters[search][4][type]=eq&filters[search][4][value]=has&filters[search][5][type]=eq&filters[search][5][value]=unmet&filters[search][6][type]=eq&filters[search][6][value]=constraints&pivot_tab=event&sort=last_seen) are caused by the "Currently running time entry has unmet constraints" error.

Investigate why the error occurs in the first place.
Prevent this error from occurring (by fixing the UI, applying automatic fix in the library, or some other way).
If that's not possible and the user scenario is acceptable for us, exclude this error from Bugsnag reporting.

### LINKED ISSUE #4513: Presence of Error Messages Within App UI
### 💻 Environment

Platform: macOS

### 📒 Description
When an error message appears in the app UI (specifically in this case, the required fields error), the error message "tray" appears to move in and out of view constantly until the error is resolved. While the error itself is necessary to knowing what may be happening during use of the app, the action of constantly moving in and out of view is distracting and has been reported to have caused occasional scroll position resets in the app ([case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/106481304667776)). 

### ⭐️ Why do you want this?
Because it's distracting in a bad way :) 

Keep the error message up as a persistent message until resolved.

### PR DESCRIPTION
**Pull request by skel35**
### 📒 Description
Stop sending requests when time entry fails to sync until there are any changes to the 

### 🕶️ Types of changes
 - **Bug fix** (non-breaking change which fixes an issue)

### 🤯 List of changes
- [x] If time entry syncing responds with "Bad Request" - stop syncing this time entry until it is edited in some way
- [x] Display the syncing error in the app UI on Windows
- [x] ~Display the syncing error in the app UI on macOS~ (was already implemented)
- [x] On app startup either make sure the unsynced time entry is shown as unsynced ~or force the time entry syncing~.
- [x] Make sure that the time entry is being synced when the app is coming back from offline mode.

### 👫 Relationships
Closes #4173
Closes #4181
Closes #4513
Closes #4310 

### 🔎 Review hints

Use Fiddler / Proxyman to observe the number of requests the app is making. There should be no repeated/looping requests returning 400.

### Offline Mode
- Unsynced time entries should be displayed as such
- When coming back from offline mode unsynced time entries should start syncing 

### Required fields feature
Needs Premium subscription
Note: You can use a Staging account (not your Toggl workspace account) in a workspace where you're an admin, and then start a Premium trial by starting the Premium subscription and stopping when you need to enter credit card details.

Set some of the fields as Required and try to create time entries from the desktop app. Observe how errors are displayed and how editing time entries makes them sync again.

### Other errors
Try other error scenarios and see if some behavior is buggy.
In particular, try doing some changes to the time entries, projects, workspace settings in the FE and see if the desktop app reacts properly.

### CODE REVIEW

**Comment by skel35** [comment]
@AndrewVebster @atsvirchkova, I would like both of you to check this out. This PR needs to be tested both on Windows and macOS, and I appreciate extra hands to try to find some scenarios that I haven't accounted for. Thanks 🙇

File: src/model/base_model.cc [hunk 1]
```diff
@@ -139,6 +140,7 @@ void BaseModel::SetUnsynced() {
 
 void BaseModel::ClearUnsynced() {
     Unsynced.Set(false);
+    ClearValidationError();
```
Comment (atsvirchkova) [inline src/model/base_model.cc:143]: Just a small remark: `Unsynced.Set(false)` here is not necessary any more as it's present in `SetValidationError` method.

**Review by atsvirchkova — APPROVED** [review]
The code looks good, and no issues found during testing. The issue with spamming requests after getting 400 feedback is fixed. 👍

File: src/model/base_model.cc (hunk 1 above)
Comment (skel35) [reply src/model/base_model.cc:142]: 👌

**Review by AndrewVebster — APPROVED** [review]
Works! No infinite error popups! 👍 🎉
